<?php

namespace AppBundle\Repository;

/**
 * BestellingRegelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestellingRegelRepository extends \Doctrine\ORM\EntityRepository
{
}
